### ISSUE TITLE
Wrong value in randint

### ISSUE THREAD

**Issue by alessandrozito98** [davidemerli/RL-generator-2020-2021#1]
https://github.com/davidemerli/RL-generator-2020-2021/blob/f235d9316e912e708f0506475e9805d8f3282ad2/main.py#L30

I think that the values in the random.randint functions should be 0,255 and not 0,256 just because 256 is not a possible value.

**Comment by davidemerli** [comment]
Yeah you're right, I also corrected the same thing with the other range (1, 128) since I mistakenly assumed the ```randint``` behaved like ```range```, but forgot about this.

Will fix right now

**Comment by davidemerli** [comment]
Done
