### ISSUE TITLE
Randomicità valori

### ISSUE THREAD

**Issue by ghost** [davidemerli/RL-generator-2020-2021#7]
Ciao! Questo non è un vero e proprio problema e non ho anche verificato se effettivamente venga risolto o meno, ma mi stavo chiedendo:  dato che genera un numero random da 0 a 255, quando ho immagini molto grandi è altamente improbabile che nella stessa immagini non abbia due pixel tali per cui il suo delta sia 255. In quel caso, per l'algoritmo che usiamo , l'immagine non viene equalizzata. Quindi in questo caso il generatore non è utile per uno stress test "veritiero", perchè nella maggior parte dei casi l'immagine in ingresso è uguale a quella in uscita. 
Secondo te ci sarebbe la possibilità di risolvere il problema? Magari diminuendo la probabilità di uscita di valori di pixel sotto il 30 o sopra il 200 per avere shift level più variegati. 

Spero di essermi spiegato bene, colgo l'occasione per ringraziarti per il tuo lavoro!

**Comment by davidemerli** [comment]
Ottima osservazione, non avendo svolto il progetto in maniera attiva ma solo il generatore ci ho fatto poco caso a questo dettaglio che invece non era da trascurare.

Ho gia' provveduto a cambiare la generazione dei valori da una distribuzione uniforme ad una gaussiana con μ = 127 e σ = 30, ed empiricamente da dei risultati piu' ragionevoli, senza tralasciare in via assoluta un possibile delta di 255

Per la deviazione standard sono andato un po' ad occhio, volendo si puo' anche alzare/abbassare un po' se serve

Se riesci a fare qualche test per controllare se va tutto bene/ti sembrano risultati accettabili ti ringrazio :)
